@startuml
!theme metal
skinparam BackgroundColor #FFFFFF-#DEDEDE

skinparam arrow {
	Thickness 2
	Color #8B8B8B
	FontColor black
    FontSize  14
}
skinparam defaultFontName       "Sans"
skinparam defaultFontSize  12
skinparam actor {
    BorderColor #8B8B8B
	BackgroundColor #316DC1
    FontColor black
    FontSize  14
}

skinparam collections {
    BorderColor #8B8B8B
    BackGroundColor #82C299
    TitleFontColor white
    FontSize  14
    text red
}

skinparam boundary {
    BorderColor #8B8B8B
	BackgroundColor #316DC1
    FontColor black
    FontSize  14    
}

skinparam sequence {
    LifeLineBackgroundColor #EE0000-#BE0000
}

hide footbox
actor User 
boundary ControlPlane
boundary DataPlane
boundary EnvironmentPlane
collections DTE
boundary PhysicalEnvironment

activate ControlPlane
activate DataPlane
activate EnvironmentPlane
activate User
activate PhysicalEnvironment

User->ControlPlane : List DTE types
ControlPlane-> DataPlane : Retrieve Info based on search criteria
return DTE List
User->ControlPlane : Create DTE
ControlPlane->DataPlane : Get DTE Definition
return DTE definition
ControlPlane->EnvironmentPlane : Create DTE
EnvironmentPlane-->DTE : Provision
activate DTE
DTE->DTE : Deploy Components
DTE->DTE : Component Discovery
DTE<<-->>PhysicalEnvironment : Initialise
DTE->DTE : Wait for ready
DTE->DTE : Ready
DTE-->ControlPlane : Status
ControlPlane->User : DTE Ready
User <--> DTE : Direct Interaction
DTE <<-->>  PhysicalEnvironment : Direct Interaction
User -> ControlPlane : Command
ControlPlane->DTE : Command
DTE-->ControlPlane : Status
User->ControlPlane : Shutdown DTE
deactivate User
ControlPlane->EnvironmentPlane : Terminate DTE
EnvironmentPlane->DTE : Terminate
destroy DTE
ControlPlane->>DataPlane : Process Output/Results

@enduml